Repository romcal/romcal, pull requests merged in 2021-05, with the labels that each got.

#273 Output all available object per days (including optionals) & Introduce `strictMode`
  README.md
  __tests__/calendar_date_overrides.test.ts
  __tests__/use_cases.test.ts
  docs/general-usage.md
  src/lib/calendar-builder.test.ts
  src/lib/calendar-builder.ts
  src/models/config/config.model.ts
  src/models/config/config.test.ts
  src/validators/config.validator.ts
Labels: discussion, documentation, enhancement

#274 Add orderBy dates syntactic sugar
  docs/general-usage.md
  src/constants/group-by-option/group-by.constant.ts
  src/lib/calendar-builder.test.ts
  src/lib/seasons.test.ts
  src/models/calendar/calendar.model.ts
Labels: enhancement

#248 Add Czech locale
  src/calendars/czechRepublic.ts
  src/locales/cs.ts
  src/locales/en.ts
  src/locales/es.ts
  src/locales/fr.ts
  src/locales/index.ts
  src/locales/it.ts
  src/locales/la.ts
  src/locales/pl.ts
  src/locales/pt-br.ts
  src/locales/sk.ts
Labels: localization

#261 Implement changes in the GRC based on the decrees from 2 Feb 2021
  src/calendars/general.ts
  src/calendars/germany.ts
  src/calendars/hungary.ts
  src/calendars/spain.ts
  src/locales/en.ts
  src/locales/es.ts
  src/locales/fr.ts
  src/locales/it.ts
  src/locales/la.ts
  src/locales/pl.ts
  src/locales/pt-br.ts
  src/locales/sk.ts
Labels: celebration

#251 Corrected Polish locale for 2.0.
  src/locales/pl.ts
Labels: localization

#277 task: localise saint Faustina Kowalska
  src/locales/fr.ts
Labels: localization

#280 Fix incorrect definitions in the czech republic calendar & Fix the drop feature so you now can ommit the date in a calendar definition
  src/calendars/czechRepublic.ts
  src/calendars/slovakia.ts
  src/models/liturgical-day/liturgical-day.types.ts
Labels: bug, celebration

#283 Makes all Sundays holy days of obligation
  src/lib/seasons.test.ts
  src/lib/seasons.ts
Labels: enhancement

#285 Remove explicit HDO definitions from celebrations that always occur o…
  src/lib/celebrations.ts
Labels: celebration
