Repository romcal/romcal, pull requests merged in 2023-08, with the labels that each got.

#446 fix: no-console in src codebase
  .eslintrc.js
  lib/models/cycles-metadata.ts
  package-lock.json
  scripts/build.ts
  scripts/bundle-doc.ts
  scripts/bundle.ts
  scripts/publish.ts
Labels: enhancement

#447 fix: calculation of days in a month to be done in UTC
  lib/utils/dates.spec.ts
  lib/utils/dates.ts
Labels: bug

#448 chore: move examples to a dedicated GitHub repository
  .eslintignore
  .npmignore
  .prettierignore
  README.md
  examples/html-web-page/README.md
  examples/html-web-page/index.html
  examples/html-web-page/package-lock.json
  examples/html-web-page/package.json
  examples/html-web-page/styles/main.css
  examples/react-app/.env
  examples/react-app/.gitignore
  examples/react-app/README.md
  examples/react-app/package.json
  examples/react-app/public/favicon.ico
  examples/react-app/public/index.html
  examples/react-app/public/logo192.png
  examples/react-app/public/logo512.png
  examples/react-app/public/manifest.json
  examples/react-app/public/robots.txt
  examples/react-app/public/romcal-logo.png
  examples/react-app/src/AppContext.tsx
  examples/react-app/src/RomcalApp.css
  examples/react-app/src/RomcalApp.test.tsx
  examples/react-app/src/RomcalApp.tsx
  examples/react-app/src/components/AdditionalLineContent.tsx
  examples/react-app/src/components/Calendar.tsx
  examples/react-app/src/components/CalendarContent.tsx
  examples/react-app/src/components/CalendarMenu.tsx
  examples/react-app/src/components/CalendarToolbar.tsx
  examples/react-app/src/components/Colors.tsx
  examples/react-app/src/components/Day.tsx
  examples/react-app/src/components/Header.tsx
  examples/react-app/src/components/Headline.tsx
  examples/react-app/src/components/LoadingIndicator.tsx
  examples/react-app/src/components/LocaleMenu.tsx
  examples/react-app/src/components/MonthPicker.tsx
  examples/react-app/src/components/RomcalHeaderLogo.tsx
  examples/react-app/src/constants/calendars.ts
  examples/react-app/src/index.css
  examples/react-app/src/index.tsx
  examples/react-app/src/react-app-env.d.ts
  examples/react-app/src/reportWebVitals.ts
  examples/react-app/src/setupTests.ts
  examples/react-app/src/stores/index.ts
  examples/react-app/src/stores/romcal.store.ts
  examples/react-app/tsconfig.json
  examples/react-app/yarn.lock
  examples/rest-api-with-express/README.md
  examples/rest-api-with-express/index.js
  examples/rest-api-with-express/package-lock.json
  examples/rest-api-with-express/package.json
  examples/rest-api-with-express/public/index.html
  examples/rest-api-with-fastify/README.md
  examples/rest-api-with-fastify/index.js
  examples/rest-api-with-fastify/package-lock.json
  examples/rest-api-with-fastify/package.json
  examples/rest-api-with-fastify/public/index.html
  jest.config.js
Labels: infrastructure

#431 translations for ES and PT-BR locales
  lib/locales/es.ts
  lib/locales/pt-br.ts
Labels: localization
