Repository romcal/romcal, pull requests merged in 2023-03, with the labels that each got.

#424 fix: xx-XX locale code ID not correctly formatted
  lib/models/config.ts
  lib/utils/string.spec.ts
  lib/utils/string.ts
  package-lock.json
  scripts/bundle.ts
  tests/locales.test.ts
Labels: bug, localization

#426 chore: fix building romcal on MS Windows (fix #425)
  scripts/build.ts
Labels: bug, infrastructure

#428 refactor: import named exports from `node:path` instead of using the default import
  scripts/build.ts
Labels: infrastructure

#427 chore: update `package-lock.json`
  package-lock.json
Labels: infrastructure
