Repository romcal/romcal, pull requests merged in 2024-06, with the labels that each got.

#579 fix(general-roman): the Passion of Saint John the Baptist should be celebrated in red
  lib/catalog/martyrology.ts
Labels: concept: calendar definitions

#571 fix(es): update 2 celebration names
  lib/locales/es.ts
Labels: change: bug, concept: localization, form: language problem

#585 ci: remove max header length
  .commitlintrc.ts
Labels: concept: infrastructure
